In [1]:
import numpy as np

### Array constructors ###

In [34]:
a = np.array([1, 2, 3])   # Create a rank 1 array from a list

In [3]:
print(type(a))            # Prints "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [4]:
print(a.shape)            # Prints "(3,)"

(3,)


In [5]:
print(a[0], a[1], a[2])   # Prints "1 2 3"

1 2 3


In [6]:
a[0] = 5                  # Change an element of the array

In [7]:
print(a)                  # Prints "[5, 2, 3]"

[5 2 3]


In [8]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array

In [9]:
print(b.shape)                     # Prints "(2, 3)"

(2, 3)


In [10]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

1 2 4


In [11]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [12]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


[[1. 1.]]


In [13]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [14]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0.]
 [0. 1.]]


In [15]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0.25984725 0.17840825]
 [0.47592368 0.2703578 ]]


In [38]:
# What if we want to create an array going from 0 to 100? 
arr = np.arange(100)
arr[-10:]

array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [39]:
# Or 10 to 100?
arr = np.arange(10,100)
arr[:10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
# If you want 100 steps from 0 to 1... 
arr = np.linspace(0, 1, 100)
arr[10:20]

array([0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919])

In [42]:
# Or if you want to generate an array from 1 to 10 
# in log10 space in 100 steps...
arr = np.logspace(0, 1, 100, base=10.0)
arr[:10]

array([1.        , 1.02353102, 1.04761575, 1.07226722, 1.09749877,
       1.12332403, 1.149757  , 1.17681195, 1.20450354, 1.23284674])

In [43]:
# Creating a 5x5 array of zeros (an image) 
image = np.zeros((5,5))
image

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [47]:
# Creating a 5x5x5 cube of 1's
# The astype() method sets the array with integer elements. 
cube = np.zeros((5,5,5)).astype(int) + 1
cube

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

* Q: Which of the above is the depth dimension?
* Q: Re-write the above using a different np API.

In [48]:
cube = np.ones((5,5,5), dtype=int)
cube

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [49]:
# With 16-bit floating-point precision... 
cube = np.ones((5, 5, 5)).astype(np.float16)
cube

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

When generating arrays, NumPy will default to the bit depth of the Python environment. If you are working with 64-bit Python, then your elements in the arrays will default to 64-bit precision. This precision takes a fair chunk memory and is not always necessary. 

### Shape of Arrays ###

In [51]:
cube.shape

(5, 5, 5)

In [53]:
# Creating an array with elements from 0 to 999 
arr1d = np.arange(1000)
arr1d.shape

(1000,)

In [54]:
# Now reshaping the array to a 10x10x10 3D array 
arr3d = arr1d.reshape((10,10,10))
arr3d.shape

(10, 10, 10)

In [56]:
# The reshape command can alternatively be called this way 
arr3d = np.reshape(arr1d, (10, 10, 10))
arr3d.shape

(10, 10, 10)

In [57]:
# Inversely, we can flatten arrays 
arr4d = np.zeros((10, 10, 10, 10)) 
arr1d = arr4d.ravel()
arr1d.shape

(10000,)

Keep in mind that the restructured arrays above are just different views of the same data in memory. This means 
that if you modify one of the arrays, it will modify the others. For example, if you set the first element of 
arr1d from the example above to 1, then the first element of arr3d will also become 1. If you don’t want this to 
happen, then use the numpy.copy function to separate the arrays memory-wise.

### Broadcasting in Numpy ###

In [28]:
# Create an array with 10^7 elements. 
arr = np.arange(1e7)

In [17]:
# Converting ndarray to list 
larr = arr.tolist()

In [19]:
# Lists cannot by default broadcast, 
# so a function is coded to emulate 
# what an ndarray can do.
def list_times(alist, scalar):
    for i, val in enumerate(alist):
        alist[i] = val * scalar 
    return alist

In [29]:
# inspect some of the elements of our array
arr[:10]

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [30]:
%%time
arr = arr * 1.1

CPU times: user 33.4 ms, sys: 81.4 ms, total: 115 ms
Wall time: 34.5 ms


In [26]:
%%time
arr = list_times(larr, 1.1)

CPU times: user 765 ms, sys: 9.58 ms, total: 774 ms
Wall time: 783 ms


The most versatile type in Numpy is __ndarray__. There is a matrix type, but it is 2-dimensional only.

In [32]:
# Creating a 3D numpy array 
arr = np.zeros((3,3,3))
arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [33]:
# Trying to convert array to a matrix, which will not work 
mat = np.matrix(arr)

ValueError: shape too large to be a matrix.

### Slicing & Indexing ###

In [67]:
alist=[[1,2],[3,4]]

In [68]:
# To return the (0,1) element we must index as shown below. 
alist[0][1]

2

In [69]:
# Converting the list defined above into an array 
arr = np.array(alist)

In [70]:
# To return the (0,1) element we use ... 
arr[0,1]

2

In [71]:
# Now to access the last column, we simply use ... 
arr[:,1]

array([2, 4])