In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array

In [3]:
print(type(a))            # Prints "<class 'numpy.ndarray'>"

<class 'numpy.ndarray'>


In [4]:
print(a.shape)            # Prints "(3,)"

(3,)


In [5]:
print(a[0], a[1], a[2])   # Prints "1 2 3"

1 2 3


In [6]:
a[0] = 5                  # Change an element of the array

In [7]:
print(a)                  # Prints "[5, 2, 3]"

[5 2 3]


In [8]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array

In [9]:
print(b.shape)                     # Prints "(2, 3)"

(2, 3)


In [10]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

1 2 4


In [14]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

[[0. 0.]
 [0. 0.]]


In [12]:
b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"


[[1. 1.]]


In [13]:
c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

[[7 7]
 [7 7]]


In [15]:
d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

[[1. 0.]
 [0. 1.]]


In [16]:
e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0.34744031 0.67490428]
 [0.06980795 0.7216412 ]]
